export const MSGS = {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  CURRENT_USER_STATE: 'CURRENT_USER_STATE',
  TOOGLE_CART: 'TOOGLE_CART',
  ADD_ITEMS: 'ADD_ITEMS',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
}
